#  Please refer to the wiki(https://github.com/nlef/moonraker-telegram-bot/wiki) for detailed information on how to configure the bot

[bot]
server: localhost
bot_token: 6209301105:AAFzbI855_wqB0eTkOFauVe8PxHmT5kuvYI
chat_id: 179442245

[camera]
host: http://localhost:8080/?action=stream

[progress_notification]
percent: 5

# [timelapse]
# time: 0
# height: 0
# cleanup: True